"""Add business setup state

Revision ID: 0d403b79dc3b
Revises: e1f27b4fe7e2
Create Date: 2026-09-25 00:08:32.150359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d403b79dc3b'
down_revision = 'e1f27b4fe7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('setup_completed_at', sa.DateTime(), nullable=True),
    sa.Column('setup_completed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['setup_completed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_transactions', schema=None) as batch_op:
        batch_op.alter_column('money_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_transactions', schema=None) as batch_op:
        batch_op.alter_column('money_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('business_settings')
    # ### end Alembic commands ###
